// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    DrawPainting: typeof import('./src/views/DrawPainting.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpCaretTop: typeof import('~icons/ep/caret-top')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpPrinter: typeof import('~icons/ep/printer')['default']
    IEpRefreshLeft: typeof import('~icons/ep/refresh-left')['default']
    IEpRefreshRight: typeof import('~icons/ep/refresh-right')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IFluentEraser20Regular: typeof import('~icons/fluent/eraser20-regular')['default']
    'IIc:RoundSave': typeof import('~icons/ic/-round-save')['default']
    IIcBaselineFormatSize: typeof import('~icons/ic/baseline-format-size')['default']
    IIcOutlinePalette: typeof import('~icons/ic/outline-palette')['default']
    IIcOutlineRectangle: typeof import('~icons/ic/outline-rectangle')['default']
    IIcRoundSave: typeof import('~icons/ic/round-save')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    Layout: typeof import('./src/views/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
